version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "47480:47480"
    environment:
      LEIN_REPL_HOST: "0.0.0.0"
      LEIN_REPL_PORT: 47480
    links:
      - db
    command: >
      sh -c "export DATABASE_URL='jdbc:postgresql://db/clj_rest_web_app_server?user=clj_rest_web_app&password=clj_rest_web_app&ssl=false' && \
             export APPLICATION_SECRET='3hPDlkV4fp2HDRoq' && \
             lein migrate && \
             lein run"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: clj_rest_web_app
      POSTGRES_PASSWORD: clj_rest_web_app
      REPL_DB: clj_rest_web_app_repl
      SERVER_DB: clj_rest_web_app_server
    volumes:
      - ./resources/docker/create_db.sh:/docker-entrypoint-initdb.d/create_databases.sh
